<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="tt" nsURI="http://www.example.org/tt" nsPrefix="tt">
  <eClassifiers xsi:type="ecore:EClass" name="University">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="roomUniquelyDefined NoOverlappingCourses roomLecturerConnectionAreSet idsAreUnique"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="course" lowerBound="1"
        upperBound="-1" eType="#//Course" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinator" upperBound="-1"
        eType="#//Coordinator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturer" upperBound="-1"
        eType="#//Lecturer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" upperBound="-1"
        eType="#//Department" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="campus" upperBound="-1"
        eType="#//Campus" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Course">
    <eStructuralFeatures xsi:type="ecore:EReference" name="coordinator" lowerBound="1"
        eType="#//Coordinator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="department" lowerBound="1"
        eType="#//Department"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeslot" lowerBound="1"
        upperBound="-1" eType="#//TimeSlot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Department">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeSlot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="room" lowerBound="1" eType="#//Room"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lecturer" lowerBound="1"
        upperBound="-1" eType="#//Lecturer" eOpposite="#//Lecturer/timeslot"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="start" lowerBound="1" eType="#//Calendar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" lowerBound="1" eType="#//Calendar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindofactivity" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Room">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mazeMapsLink" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CampusBuilding">
    <eStructuralFeatures xsi:type="ecore:EReference" name="classroom" upperBound="-1"
        eType="#//Room" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Campus">
    <eStructuralFeatures xsi:type="ecore:EReference" name="campusbuilding" upperBound="-1"
        eType="#//CampusBuilding" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Lecturer" eSuperTypes="#//Person">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="noLecturesAtTheSameTime"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="timeslot" upperBound="-1"
        eType="#//TimeSlot" eOpposite="#//TimeSlot/lecturer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Coordinator" eSuperTypes="#//Person"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Calendar" instanceClassName="java.util.Calendar"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Activity">
    <eLiterals name="Lecture"/>
    <eLiterals name="Exercise" value="1"/>
    <eLiterals name="Supervision" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
