/**
 *
 * $Id$
 */
package no.ntnu.idi.tdt4250.tt.validation;

import no.ntnu.idi.tdt4250.tt.Coordinator;
import no.ntnu.idi.tdt4250.tt.Department;
import no.ntnu.idi.tdt4250.tt.TimeSlot;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link no.ntnu.idi.tdt4250.tt.Course}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CourseValidator {
	boolean validate();

	boolean validateCoordinator(Coordinator value);

	boolean validateDepartment(Department value);

	boolean validateName(String value);

	boolean validateTimeslot(EList<TimeSlot> value);
}
