/**
 *
 * $Id$
 */
package no.ntnu.idi.tdt4250.tt.validation;

/**
 * A sample validator interface for {@link no.ntnu.idi.tdt4250.tt.Person}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PersonValidator {
	boolean validate();

	boolean validateFirstName(String value);

	boolean validateLastName(String value);

	boolean validateID(int value);
}
