/**
 *
 * $Id$
 */
package no.ntnu.idi.tdt4250.sr.validation;

import java.util.Calendar;

import no.ntnu.idi.tdt4250.sr.Campus;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link no.ntnu.idi.tdt4250.sr.CoursePeriod}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CoursePeriodValidator {
	boolean validate();

	boolean validateCampus(EList<Campus> value);

	boolean validateStart(Calendar value);

	boolean validateEnd(Calendar value);
}
