/**
 */
package no.ntnu.idi.tdt4250.sr.provider;

import java.util.ArrayList;
import java.util.Collection;

import no.ntnu.idi.tdt4250.sr.util.SrAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class SrItemProviderAdapterFactory extends SrAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public SrItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.Courses} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CoursesItemProvider coursesItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.Courses}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCoursesAdapter() {
		if (coursesItemProvider == null) {
			coursesItemProvider = new CoursesItemProvider(this);
		}

		return coursesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.CourseRequirement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CourseRequirementItemProvider courseRequirementItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.CourseRequirement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCourseRequirementAdapter() {
		if (courseRequirementItemProvider == null) {
			courseRequirementItemProvider = new CourseRequirementItemProvider(this);
		}

		return courseRequirementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.CoursePeriod} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CoursePeriodItemProvider coursePeriodItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.CoursePeriod}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCoursePeriodAdapter() {
		if (coursePeriodItemProvider == null) {
			coursePeriodItemProvider = new CoursePeriodItemProvider(this);
		}

		return coursePeriodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.Campus} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CampusItemProvider campusItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.Campus}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCampusAdapter() {
		if (campusItemProvider == null) {
			campusItemProvider = new CampusItemProvider(this);
		}

		return campusItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.CampusBuilding} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected CampusBuildingItemProvider campusBuildingItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.CampusBuilding}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createCampusBuildingAdapter() {
		if (campusBuildingItemProvider == null) {
			campusBuildingItemProvider = new CampusBuildingItemProvider(this);
		}

		return campusBuildingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.Room} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RoomItemProvider roomItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.Room}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRoomAdapter() {
		if (roomItemProvider == null) {
			roomItemProvider = new RoomItemProvider(this);
		}

		return roomItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.TimeSlot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TimeSlotItemProvider timeSlotItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.TimeSlot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createTimeSlotAdapter() {
		if (timeSlotItemProvider == null) {
			timeSlotItemProvider = new TimeSlotItemProvider(this);
		}

		return timeSlotItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link no.ntnu.idi.tdt4250.sr.Lecturer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LecturerItemProvider lecturerItemProvider;

	/**
	 * This creates an adapter for a {@link no.ntnu.idi.tdt4250.sr.Lecturer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLecturerAdapter() {
		if (lecturerItemProvider == null) {
			lecturerItemProvider = new LecturerItemProvider(this);
		}

		return lecturerItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (coursesItemProvider != null)
			coursesItemProvider.dispose();
		if (courseRequirementItemProvider != null)
			courseRequirementItemProvider.dispose();
		if (coursePeriodItemProvider != null)
			coursePeriodItemProvider.dispose();
		if (campusItemProvider != null)
			campusItemProvider.dispose();
		if (campusBuildingItemProvider != null)
			campusBuildingItemProvider.dispose();
		if (roomItemProvider != null)
			roomItemProvider.dispose();
		if (timeSlotItemProvider != null)
			timeSlotItemProvider.dispose();
		if (lecturerItemProvider != null)
			lecturerItemProvider.dispose();
	}

}
